### ISSUE TITLE
move the repository

### ISSUE THREAD

**Issue by fippo** [fippo/rtcstats-server#260]
This project has been hosted in the opentok repo for quite some time after I left and continued to work on it. Thanks @baddn for the decision to opensource it and let me continue working on it.

But it remains rather detached from the org so I'd like to move it along with the js while keeping license and attribution as is. Not sure if I need an organisation, will probably live on my account for now.

cc @cferran

**Comment by fippo** [comment]
also it seems I can't enable travis?

**Comment by cferran** [comment]
@fippo I am OK with that.

**Comment by fippo** [comment]
Done, thank you!

**Comment by fippo** [comment]
@cferran @aullman can one of you help with https://github.com/opentok/rtcstats by making me an admin so I can move it too?

**Comment by fippo** [comment]
Done. Thanks @odivorra
