### ISSUE TITLE
BigQuery ignore unknown values

### ISSUE THREAD

**Issue by milen-yordanov** [fippo/rtcstats-server#326]
Running the server with BigQuery storage causes errors like:
`No such field: audioGoogResidualEchoLikelihoodRecentMaxMean`

I suppose the workaround for this case is to use config.fields and to specify ALL columns in the table.

Wouldn't it be better to modify
```
bigquery
  .dataset(config.dataset)
  .table(config.table)
  .load(filename, { format: 'JSON'})
```

to 

```
bigquery
  .dataset(config.dataset)
  .table(config.table)
  .load(filename, { format: 'JSON', ignoreUnknownValues: true })
```

**Comment by fippo** [comment]
That sounds like a better solution indeed, thank you!
@juandebravo can you give the PR a spin?
